plugins:
  - checksum: bbe1b55319616c93b4b473c32fdb2e62546e1104aa3d9903fdca1db533f515fe02f032cd3296000a1a7fb62cb6b119f30d4720046afd5d34a4e1f918715b1777
    path: .yarn/plugins/@yarnpkg/plugin-nextjs-transpile-list.cjs
    spec: .yarn/workspace/nextjs-transpile-list/bundles/@yarnpkg/plugin-nextjs-transpile-list.js

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
